{\rtf1\ansi\ansicpg1251\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 .AppleSystemUIFontMonospaced-Regular;}
{\colortbl;\red255\green255\blue255;\red24\green26\blue30;}
{\*\expandedcolortbl;;\cssrgb\c12157\c13725\c15686;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl394\partightenfactor0

\f0\fs27\fsmilli13600 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 name: Sync Leetcode\
\
on:\
  workflow_dispatch:\
  schedule:\
    - cron: "0 8 * * 6"\
\
jobs:\
  build:\
    runs-on: ubuntu-latest\
\
    steps:\
      - name: Sync\
        uses: joshcai/leetcode-sync@v1.5\
        with:\
          github-token: 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
          leetcode-csrf-token: $\{\{ secrets.LEETCODE_CSRF_TOKEN \}\}\
          leetcode-session: $\{\{ secrets.LEETCODE_SESSION \}\}\
          destination-folder: my-folder\
}
